### ISSUE TITLE
import-local not work for windows when gloab module and local module in different drive

### ISSUE THREAD

**Issue by slgluo** [sindresorhus/import-local#10]
As mentioned in the title, in this line:
`const filenameInLocalNodeModules = !path.relative(localNodeModules, filename).startsWith('..');`
`filenameInLocalNodeModules ` always `true`，because `path.relative(localNodeModules, filename)` always return `filename`. However, it is a absolute path and it does not start with “..”

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/import-local/pull/9
